apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nano-demo-1
  name: nano-demo-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nano-demo-1

  template:
    metadata:
      labels:
        app: nano-demo-1
    spec:
      containers:
        - image: sulaynd/nano-demo:0.0.1-SNAPSHOT
          name: nano-demo-1
          imagePullPolicy: Always
          ports:
            - containerPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: nano-service-1
  labels:
    app: nano-service-1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9002
      protocol: TCP
  selector:
    app: nano-demo-1
